import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Check, Ruler } from "lucide-react";
import { Link } from "wouter";

export default function Pricing() {
  const { data: plans, isLoading } = trpc.billing.plans.useQuery();
  return <div className="min-h-dvh bg-slate-950 text-slate-50"><header className="border-b border-white/10"><div className="container flex items-center justify-between py-4"><Link href="/" className="flex items-center gap-2 font-semibold"><Ruler className="h-5 w-5 text-cyan-400" />Roof Plan Measurer</Link><Link href="/login"><Button variant="outline" className="border-white/20 text-slate-50 hover:bg-white/10">Sign in</Button></Link></div></header><main className="container py-14"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Simple, commercial-ready pricing</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">Start measuring before you pay.</h1><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-300">Every workspace begins with a 14-day trial. No credit card is required.</p></div><div className="mx-auto mt-12 grid max-w-5xl gap-5 md:grid-cols-3">{isLoading ? Array.from({ length: 3 }).map((_, i) => <div key={i} className="h-80 animate-pulse rounded-xl bg-white/10" />) : plans?.length ? plans.map(plan => <Card key={plan.id} className="border-white/15 bg-white text-slate-950"><CardHeader><CardTitle>{plan.name}</CardTitle><CardDescription>{plan.description || "Commercial roof takeoff workspace"}</CardDescription><p className="pt-4 text-3xl font-bold">${(plan.priceCents / 100).toFixed(0)}<span className="text-sm font-normal text-muted-foreground">/{plan.billingInterval}</span></p></CardHeader><CardContent className="space-y-2 text-sm"><p className="flex gap-2"><Check className="h-4 w-4 text-emerald-600" />{plan.maxProjects ?? "Unlimited"} projects</p><p className="flex gap-2"><Check className="h-4 w-4 text-emerald-600" />{plan.maxSeats ?? "Unlimited"} seats</p><p className="flex gap-2"><Check className="h-4 w-4 text-emerald-600" />PDF reports and CSV export</p></CardContent><CardFooter><Link href="/signup" className="w-full"><Button className="w-full">Start 14-day trial</Button></Link></CardFooter></Card>) : <Card className="md:col-span-3"><CardContent className="p-8 text-center text-muted-foreground">Subscription plans are being finalized. Create your workspace now and start the included trial.</CardContent></Card>}</div></main></div>;
}
